name: Output information
on: [workflow_dispatch, issues]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output github context
        run: echo "${{toJSON(github)}}" #github actions functions, github actions context
